version: '3'

services:
    mongo:
        image: mongo
        ports:
          - 27017:27017
        networks:
          - overlay
    express:
        image: tvaisanen/dmapper-demo-server-23-11
        ports:
          - 3000:3000
        networks:
          - overlay
        environment:
          MONGO_PATH: mongo
          MONGO_PORT: 27017
          DB_NAME: demo
    web:
        image: tvaisanen/dmapper-demo-webapp-23-11
        networks:
            - overlay
        command: npm start
        ports:
            - 3001:3000
        environment:
          REACT_APP_ENV: demo
          REACT_APP_API_HOST: localhost:3000

networks:
   overlay:
             
