version: '3'

# setting is the same as in development
# but the env has PERSIST_DATA=True
# which disables the server resetting
# and there is no pre inserted data

services:

    mongo:
        image: mongo
        ports:
          - 27017:27017
        networks:
          - overlay

    express:
        build: ./services/express-server
        ports:
          - 3000:3000
        volumes:
          - ./services/express-server/src/:/usr/local/src/express/src
        env_file:
         - .env-development
        environment:
          - DB_NAME=persistent-data
        networks:
          - overlay

    web:
        build: ./services/web
        volumes:
            - ./services/web/src/:/usr/webapp/src/src
            - ./services/web/package.json:/usr/webapp/src/package.json
            - ./services/web/.flowconfig:/usr/webapp/src/.flowconfig
        networks:
            - overlay
        command: npm start
        ports:
            - 3001:3000
        env_file:
            - .env-development
        environment:
          - REACT_APP_PERSIST_DATA=1

networks:
   overlay:
             
