version: '3'

services:

    mongo:
        image: mongo
        ports:
          - 27017:27017
        networks:
          - overlay

    express:
        build: ./express-server
        ports:
          - 3000:3000
        volumes:
          - ./express-server/src/:/usr/local/src/express/src
        environment:
          NODE_ENV: development
          MONGO_PATH: mongo
          MONGO_PORT: 27017
          DB_NAME: test
        networks:
          - overlay

    web:
        build: ./web
        volumes:
            # todo: refactor to .env
            - ./web/src/:/usr/webapp/src/src
            - ./.env:/usr/webapp/src/.env
        networks:
            - overlay
        command: npm start

        # hide ports. access only via proxy
        ports:
            - 3001:3000
        env_file:
            - .env
        environment:
          REACT_APP_API_HOST: "localhost:3000"
          REACT_APP_API_PORT: 3000

    integration-test-runner:
        build: ./services/selenium-driver
        volumes:
            - ./services/integration-test/test/:/usr/integration-tests/test
        container_name: integration-test-runner
        networks:
            - overlay
        command: npm test
        environment:
            - WEBAPP_HOST=web

    selenium-hub:
        image: selenium/hub:3.141.59-bismuth
        container_name: selenium-hub
        ports:
        - "4444:4444"
        networks:
          - overlay
    chrome:
        image: selenium/node-chrome:3.141.59-bismuth
        depends_on:
        - selenium-hub
        environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        networks:
          - overlay


    firefox:
        image: selenium/node-firefox:3.141.59-bismuth
        depends_on:
        - selenium-hub
        environment:
        - HUB_HOST=selenium-hub
        - HUB_PORT=4444
        networks:
          - overlay

networks:
   overlay:
             
