version: '3'

services:
    moin:
        image: tvaisanen/gwiki-with-moin
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - ./wiki/plugin/:/usr/local/lib/python2.7/dist-packages/graphingwiki/plugin
            #- ./wiki/pages/:/srv/wikis/collab/wikis/collab/data/pages
            - ./wiki/start.sh:/usr/local/start.sh
        command: bash /usr/local/start.sh
        networks:
            - overlay

    proxy:
        build: ./services/proxy
        image: proxy
        volumes:
            - ./services/proxy/default.with-moin.conf:/etc/nginx/conf.d/default.conf:ro
            - ./services/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./services/proxy/site-enabled/:/etc/nginx/site-enabled/:ro
            - ./services/proxy/ssl/:/etc/nginx/ssl/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - overlay
        depends_on:
          - api
          - web
          - moin
        env_file:
            - .env
    db:
        image: postgres
        volumes:
            - dmapper-data:/var/lib/postgresql/data
        networks:
            - overlay
        ports:
            - "5432:5432"

    web:
        build: ./services/web
        volumes:    
            # todo: refactor to .env
            - ./services/web/:/usr/webapp/src
            - ./.env:/usr/webapp/src/.env
        networks:
            - overlay
        command: bash docker-entrypoint.sh

        # hide ports. access only via proxy
        # ports:
             #- "3000:3000"
        env_file:
            - .env
        environment:
            - MESSAGE="Hello"

    api: 
        build: ./dependencymapping 
        volumes:
            # todo: refactor to .env
            - ./dependencymapping/:/usr/api/src
        # hide ports. access only via proxy
        # ports:
             #- "8000:8000"
        command: bash docker-entrypoint.sh 
        networks:
            - overlay
        depends_on:
            - db
        env_file:
            - .env

volumes:
   dmapper-data:
           
networks:
   overlay:
             
