version: '3'

services:

    mongo:
        image: mongo
        ports:
          - 27017:27017
        networks:
          - overlay

    express:
        build: ./express-server
        ports:
          - 3000:3000
        env_file:
            - .env-demo
        networks:
          - overlay

    web:
        build: ./web
        networks:
            - overlay
        command: npm start
        ports:
            - 3001:3000
        env_file:
            - .env-demo

networks:
   overlay:
             
