version: '3'

services:
    proxy:
        build: ./proxy
        image: proxy
        volumes:
            - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./proxy/site-enabled/:/etc/nginx/site-enabled/:ro
        ports:
            - "80:80"
        networks:
            - overlay
        depends_on:
          - api
          - web
        env_file:
            - .env
    db:
        image: postgres
        volumes:
            - psgl-dm:/var/lib/postgresql/data
        networks:
            - overlay
        ports:
            - "5432:5432"
    web: 
        build: ./web
        volumes:    
            # todo: refactor to .env
            - /home/tvaisanen/OUSPG/dependencymapping/web/:/usr/webapp/src
            - ./.env:/usr/webapp/src/.env
        networks:
            - overlay
        command: bash docker-entrypoint.sh
        # hide ports. access only via proxy
        # ports:
             #- "3000:3000"
        env_file:
            - .env
        environment:
            - MESSAGE="Hello"

    api: 
        build: ./dependencymapping 
        volumes:
            # todo: refactor to .env
            - /home/tvaisanen/OUSPG/dependencymapping/dependencymapping/:/usr/api/src
        # hide ports. access only via proxy
        # ports:
             #- "8000:8000"
        command: bash docker-entrypoint.sh 
        networks:
            - overlay
        depends_on:
            - db
        env_file:
            - .env

volumes:
   psgl-dm:
           
networks:
   overlay:
             
