version: '3'

services:
    db:
        image: postgres
        volumes:
            - psgl-dm:/var/lib/postgresql/data
        networks:
            - overlay
        ports:
            - "5432:5432"
    web: 
        build: ./web
        volumes:    
            # todo: refactor to .env
            - /home/tvaisanen/OUSPG/dependencymapping/web/:/usr/webapp/src
              
        networks:
            - overlay
        command: bash docker-entrypoint.sh 
        ports:
            - "3000:3000"
    api: 
        build: ./dependencymapping 
        volumes:
            # todo: refactor to .env
            - /home/tvaisanen/OUSPG/dependencymapping/dependencymapping/:/usr/api/src
        ports:
            - "8000:8000"
        command: bash docker-entrypoint.sh 
        networks:
            - overlay
        depends_on:
            - db


volumes:
   psgl-dm:
           
networks:
   overlay:
             
