version: '3.1'

services:
    mongo:
        image: mongo
        networks:
          - closed
        # Allow access only in closed network
        # enabled for development
        ports:
          - 27017:27017

    api:
        build:
          context: ./services/express-server
          dockerfile: Dockerfile
        ports:
          - 3000:3000
        volumes:
          - ./services/express-server/src/:/usr/local/src/express/src
          - ./services/express-server/test/:/usr/local/src/express/test
        environment:
          - MONGO_PATH=mongo
          - MONGO_PORT=27017
          - DB_NAME=development

        secrets:
          - public-api-path

        networks:
          - closed # To access the database
          - public # To communicate with clients
        depends_on:
          - mongo

    app:
        ## build the web application to
        ## be deployed as static files
        ## served by NGINX

        build:
          context: ./services/web
          dockerfile: Dockerfile
        networks:
          - public
        command: npm start
        ports:
          - 3001:3000
        volumes:
          - ./services/web/src/:/usr/webapp/src/src
          - ./services/web/package.json:/usr/webapp/src/package.json
          - ./services/web/.flowconfig:/usr/webapp/src/.flowconfig
        environment:
          - REACT_APP_API_PATH=/api
          - REACT_APP_API_PORT=
          - REACT_APP_API_HOST=/api
          - REACT_APP_PERSIST_DATA=true

    nginx:
        build:
          context: ./services/proxy
          dockerfile: Dockerfile-dev
        volumes:
          - ./services/proxy/default.dev.conf:/etc/nginx/conf.d/default.conf
          - ./services/proxy/nginx.conf:/etc/nginx/nginx.conf
          - ./services/proxy/site-enabled/:/etc/nginx/site-enabled
          - ./services/certbot/data/:/data/certbot

        networks:
          - public
          - closed
        ports:
          - 8080:80
          - 8443:443
        tty: true
        stdin_open: true
        depends_on:
          - app
          - api
        environment:
          - API_PATH=api
          - API_PORT=3000
          - MONGO_PATH=mongo
          - MONGO_PORT=27017
          - DB_NAME=development

networks:
   closed:
   public:

secrets:
  public-api-path:
    file: ./secrets/public-api-path.txt
             
