version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./dependencymapping/db.sqlite3:/src/db.sqlite
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
