version: '3'

services:
    mongo:
        image: mongo
        networks:
          - closed
        # Allow access only in closed network
        # ports:
        #    - 27017:27017

    api:
        build:
          context: ./services/express-server
          dockerfile: Dockerfile-dist
        ports:
          - 3000:3000
        volumes:
          - ./services/express-server/src/:/usr/local/src/express/src
        environment:
          - MONGO_PATH=mongo
          - MONGO_PORT=27017
          - DB_NAME=production

        networks:
          - closed # To access the database
          - public # To communicate with clients
        depends_on:
          - mongo

    build-web:
        ## build the web application to
        ## be deployed as static files
        ## served by NGINX

        build:
          context: ./services/web
          dockerfile: Dockerfile-dist
        command: npm run build
        volumes:
          - static-webapp:/usr/webapp/src/build
        environment:
          - REACT_APP_API_PATH=/api
          - REACT_APP_API_PORT=

    nginx:
        build:
          context: ./services/proxy
          dockerfile: Dockerfile-dist
        networks:
          - public
          - closed
        volumes:
          - static-webapp/:/www/webapp/
        ports:
          - 8080:80
          - 8443:443
        tty: true
        stdin_open: true
        depends_on:
          - build-web
          - api
        environment:
          - API_PATH=api
          - API_PORT=3000
          - MONGO_PATH=mongo
          - MONGO_PORT=27017
          - DB_NAME=production

networks:
   closed:
   public:
             
volumes:
  static-webapp: