version: '3'

services:

    mongo:
        image: mongo
        ports:
          - 27017:27017
        networks:
          - overlay

    express:
        build: ./services/express-server
        ports:
          - 3000:3000
        volumes:
          - ./services/express-server/src/:/usr/local/src/express/src
          - ./services/express-server/test/:/usr/local/src/express/test
        environment:
          NODE_ENV: development
          MONGO_PATH: mongo
          MONGO_PORT: 27017
          DB_NAME: test
          TEST_DATA: __test__/unit-tests
        networks:
          - overlay

networks:
   overlay:
             
