version: '3'

services:

    mongo:
        image: mongo
        ports:
          - 27017:27017
        networks:
          - overlay

    express:
        build: ./services/express-server
        ports:
          - 3000:3000
        volumes:
          - ./services/express-server/src/:/usr/local/src/express/src
        environment:
          NODE_ENV: development
          MONGO_PATH: mongo
          MONGO_PORT: 27017
          DB_NAME: test
          # data in development can be edited
          # without affecting unit tests
          TEST_DATA: __test__/development
        networks:
          - overlay

    web:
        build: ./services/web
        volumes:
            - ./services/web/src/:/usr/webapp/src/src
        networks:
            - overlay
        command: npm start

        # hide ports. access only via proxy
        ports:
            - 3001:3000
        env_file:
            - .env
        environment:
          REACT_APP_API_HOST: "localhost:3000"
          REACT_APP_API_PORT: 3000


networks:
   overlay:
             
